;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Sun Nov 8 2023
; Processor: 8086
; Compiler:  MASM32
;====================================================================
DATA SEGMENT   
    ; 8255
    PORTA EQU 0C0H  		; PORTA ADDRESS                                       
    PORTB EQU 0C2H  		; PORTB ADDRESS                                     
    PORTC EQU 0C4H  		; PORTC ADDRESS    
    COMREG EQU 0C6H  		; COMMAND REGISTER   
    
    ; 8253
    CLOCK0 EQU 0C8H 		; COUNTER
    CLOCK1 EQU 0CAH
    CLOCK2 EQU 0CCH
    T_COMREG EQU 0CEH		; COUNTER COMMAND REGISTER	     
    
    ; VARIABLES	
    NUM DB 3FH, 06H, 5BH, 4FH, 66H, 6DH, 7DH, 07H, 7FH, 6FH 
    DIGIT DB 0d                                                                  
DATA ENDS
CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA

START:
    INIT:
    ;SETUP THE 8253
    XOR AL, AL
    MOV AL, 00111000B  ; CWORD
    OUT T_COMREG, AL         
    CALL CLOCK_RESET
    
    ;SETUP THE 8255 
    XOR AL, AL
    MOV AL, 10001001B ; COMMAND BYTE A 
    OUT COMREG, AL
    
    MAIN:        
        CALL DISPLAY_NUM
           
    NEXTPHASE:
    JMP MAIN
DISPLAY_NUM PROC 
    ; SETUP
    XOR AX, AX   
    LEA SI, NUM  
    MOV DX, PORTA
    
    ; SETTING UP THE CORRECT LED PATTERN
    MOV AL, [DIGIT]   
    ADD SI, AX
    MOV AL, [SI]
    
    ; OUTPUTING THE LED PATTERN TO PORTA
    OUT DX, AL   
    XOR AX, AX
    RET
DISPLAY_NUM ENDP 

CLOCK_RESET PROC
    XOR AX, AX
    MOV DX, CLOCK0
    MOV AL, 0D0H
    OUT DX, AL   
    MOV AL, 07H
    OUT DX, AL
    RET
CLOCK_RESET ENDP 


DELAY PROC                 
    MOV CX, 0FFFFH
DELAY_LOOP:
    DEC CX
    CMP CX, 00H
    JNZ DELAY_LOOP
    RET
DELAY ENDP
	
CODE ENDS
END START
